# Info
title: Art of Academia Podcast
description: A weekly podcast hosted by Dr. Komal Gupta and Dr. Madan Mohan, featuring interviews with leading scientists about research experiences, challenges, and life in academia.
url: https://artofacademia.com/
baseurl: ''
image: /assets/images/podcast-logo.jpeg

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
